name: Create Archive
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git*'
    - uses: actions/upload-artifact@v2
      with:
        name: HKUST-Timetable-Addon-Release
        path: 'release.zip'